# Site settings
name: Hospice MICHOAGAN
title: Hospice MICHOAGAN | Cybersecurity professional
description: Cybersecurity professional focused on penetration testing, real time security event monitoring and security incident investigation.
url: https://michpice.github.io/
baseurl: ''
email: hospicemichoagan04g@gmail.com
cover: https://michpice.github.io/img/og.png
logo: https://michpice.github.io/img/emojis/rocket.png
resume: https://michpice.github.io/resume.pdf
social:
  - title: email
    url: mailto:hospicemichoagan04@gmail.com
  - title: twitter
    url: https://twitter.com/michpice
  - title: instagram
    url: https://instagram.com/michpice
  - title: codepen
    url: http://codepen.io/michpice
  - title: github
    url: https://github.com/michpice
  - title: linkedin
    url: https://www.linkedin.com/in/hospice-michoagan/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
